### ISSUE TITLE
"Videos récentes" ne ramène que 2 videos....

### ISSUE THREAD

**Issue by Raiedecharles** [thomas-ernest/plugin.video.arteplussept#38]
"Vidéos récentes" ne ramène que 2 videos sur une version récente du plugin (une liste de plusieurs videos sur une ancienne version)

**Comment by thomas-ernest** [comment]
Peux-tu fournir plus d’info stp ? Screenshots, logs, etc...
La catégorie "vidéos récentes" n'existe pas. Il y a "reprendre la lecture" ou "mon historique".
Les vidéos dans ces catégories sont gérées par Arte. Tu peux comparer entre ce que tu vois sur arte.tv > Mon profil et le plugin.

Je me permets de fermer le bug. Je te laisse le rouvrir si tu fournis des infos supplémentaires.
