### ISSUE TITLE
Mismatch of quality definitions

### ISSUE THREAD

**Issue by maaaaz** [thomas-ernest/plugin.video.arteplussept#39]
Hello there,

This file contains quality parameters: 
https://github.com/thomas-ernest/plugin.video.arteplussept/blob/8d1ade5e63e6325f72c6653fa59f4ced497fc856/resources/settings.xml#L15

But it seems there is a mismatch of values: having "SQ" with "High Quality", "High" with "Low Quality" is not consistent: 
* `High Quality (HQ)` should be `HQ`
* and `Soft Quality (SQ)` should be `Low`.

Not the opposite.

Cheers.

**Comment by thomas-ernest** [comment]
Hello @maaaaz ,

I agree that quality mapping/naming is misleading. I double checked Arte HBB TV API and I confirm that SQ is for High Quality 720p , EQ is for Medium Quality 406p and HQ is for Low Quality 360p. You can look at the log attached : [20231226_184633564184_hbbtv_streams.json](https://github.com/thomas-ernest/plugin.video.arteplussept/files/13773032/20231226_184633564184_hbbtv_streams.json)

I will open a PR to rename configuration to avoid this misleading situation. Please review and approve. If you can test it upfront, it would be great.

Thank you,
Best regards,

**Comment by thomas-ernest** [comment]
to be released soon.

**Comment by thomas-ernest** [comment]
Released in version 1.4.2, available in official kodi repo : https://github.com/xbmc/repo-plugins/pull/4443
