### ISSUE TITLE
Make repository more visible

### ISSUE THREAD

**Issue by goggle** [thomas-ernest/plugin.video.arteplussept#9]
If this is the official continuation of the Kodi Arte+7 plugin, we should make it more visible.

I suggest the following steps:

- Archive the ``old``repository https://github.com/known-as-bmf/plugin.video.arteplussept
- Mostly remove the README in https://github.com/known-as-bmf/plugin.video.arteplussept and add a link to the new official continuation.
- Change the sources in `addon.xml`, so that people will more easily discover this repository, e.g. if they land on this page: https://kodi.tv/addons/matrix/plugin.video.arteplussept

**Comment by thomas-ernest** [comment]
Hello,

Thank you for your suggestion.

- addon.xml updated with commit [58bdb00dc1](https://github.com/thomas-ernest/plugin.video.arteplussept/commit/58bdb00dc1bd768b3b743fb65b84c15598babcf3) to imporved referencing tools and wikis.

- Update of bmf's readme with [PR#84](https://github.com/known-as-bmf/plugin.video.arteplussept/pull/84) open. 
- Archiving of BMF's can only be done by repo owner / BMF after merging PR#84. Pre-requisites for this step : closing issues, open PRs... are done.

I will soon close this issue. Please let me know, if something can still be improved.

**Comment by goggle** [comment]
Perfect, thanks!
